experimentName: random_forest_optimization
trialConcurrency: 1
maxTrialNumber: 20
searchSpaceFile: /users/k21116947/ABCD/trail4/search_space.json
trialCommand: python3 /users/k21116947/ABCD/trail4/trail.py
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local