[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "notebooks"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["./utils"]
include = ["utils*"]